source 'https://rubygems.org'
gem 'activerecord', '~>4.2.4'
gem 'activesupport', '~>4.2.4'
gem 'faker', '~>1.5.0'
gem 'sqlite3', '~>1.3.11'
gem 'minitest', '5.8.2'
gem 'nokogiri'
gem 'htmlbeautifier'
