defaults:
  :max_daily_transactions: 800
  :min_stock_per_item: 10
  :max_stock_per_item: 99
  :unique_items: 100
  :vendors: 5
  :employees: 6
  :max_price: 100
  :max_unique_per_sale: 15
  :db_name:

promotions:
  :three_for_two: "( qty / 3 ) * price"
  :two_for_one: "( qty / 2 ) * price"
  :second_half_price: "( qty / 2 ) * ( price / 2 )"
