products:
  :vendor_id: integer
  :title: string
  :author: string
  :price: decimal
  :in_stock: integer
  :min_stock: integer

transactions:
  :employee_id: integer
  :product_id: integer
  :date: string
  :price: decimal
  :result: string

vendors:
  :name: string

employees:
  :name: string
  :title: string
