setup_table_books: >
  CREATE TABLE IF NOT EXISTS Books (
    id INTEGER PRIMARY KEY,
    sku TEXT,
    title TEXT,
    author TEXT,
    price REAL
    )

setup_table_ledger: >
  CREATE TABLE IF NOT EXISTS Ledger (
    id INTEGER PRIMARY KEY,
    date TEXT,
    sku TEXT,
    price REAL,
    result TEXT
    )

setup_table_stock: >
  CREATE TABLE IF NOT EXISTS Stock (
    id INTEGER PRIMARY KEY,
    sku TEXT,
    quantity INT
    )

add_to_stock: >
  INSERT INTO Stock VALUES (null, ?, ?)

add_to_ledger: >
  INSERT INTO Ledger VALUES (null, ?, ?, ?, ?)

add_to_books: >
  INSERT INTO Books VALUES (null, ?, ?, ?, ?)

update_stock: >
  UPDATE Stock SET quantity = quantity - 1 WHERE sku = ? AND quantity > 0

bestsellers: >
  SELECT b.title, b.author, l.sku, COUNT(l.sku), SUM(l.price)
  FROM Ledger l JOIN Books b ON b.sku = l.sku
  WHERE result = "sold"
  GROUP BY l.sku
  ORDER BY COUNT(l.sku) DESC, SUM(l.price) DESC LIMIT ?

get_ledger: >
  SELECT l.date, l.sku, b.title, b.author, l.price, l.result
  FROM Ledger l JOIN Books b ON b.sku = l.sku

random_book: >
  SELECT * FROM Books ORDER BY RANDOM() LIMIT 1

an_item: >
  SELECT b.price, s.quantity
  FROM Books b
  JOIN Stock s ON s.sku = b.sku WHERE b.sku = ? LIMIT 1

item_stock: >
  SELECT quantity FROM Stock WHERE sku = ?

ledger_item: >
  SELECT SUM(price) FROM Ledger WHERE sku = ?
